// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculadora.proto

package ufc.sd.calc;

public final class Calculadora {
  private Calculadora() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:br.ufc.quixada.calc.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required double n1 = 2;</code>
     */
    boolean hasN1();
    /**
     * <code>required double n1 = 2;</code>
     */
    double getN1();

    /**
     * <code>required double n2 = 3;</code>
     */
    boolean hasN2();
    /**
     * <code>required double n2 = 3;</code>
     */
    double getN2();

    /**
     * <code>repeated .br.ufc.quixada.calc.Request.Operacao op = 4;</code>
     */
    java.util.List<ufc.sd.calc.Calculadora.Request.Operacao> getOpList();
    /**
     * <code>repeated .br.ufc.quixada.calc.Request.Operacao op = 4;</code>
     */
    int getOpCount();
    /**
     * <code>repeated .br.ufc.quixada.calc.Request.Operacao op = 4;</code>
     */
    ufc.sd.calc.Calculadora.Request.Operacao getOp(int index);
  }
  /**
   * Protobuf type {@code br.ufc.quixada.calc.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:br.ufc.quixada.calc.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      id_ = 0;
      n1_ = 0D;
      n2_ = 0D;
      op_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              n1_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              n2_ = input.readDouble();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              ufc.sd.calc.Calculadora.Request.Operacao value = ufc.sd.calc.Calculadora.Request.Operacao.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                  op_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000008;
                }
                op_.add(rawValue);
              }
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                ufc.sd.calc.Calculadora.Request.Operacao value = ufc.sd.calc.Calculadora.Request.Operacao.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(4, rawValue);
                } else {
                  if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                    op_ = new java.util.ArrayList<java.lang.Integer>();
                    mutable_bitField0_ |= 0x00000008;
                  }
                  op_.add(rawValue);
                }
              }
              input.popLimit(oldLimit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          op_ = java.util.Collections.unmodifiableList(op_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ufc.sd.calc.Calculadora.internal_static_br_ufc_quixada_calc_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ufc.sd.calc.Calculadora.internal_static_br_ufc_quixada_calc_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ufc.sd.calc.Calculadora.Request.class, ufc.sd.calc.Calculadora.Request.Builder.class);
    }

    /**
     * Protobuf enum {@code br.ufc.quixada.calc.Request.Operacao}
     */
    public enum Operacao
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SOM = 0;</code>
       */
      SOM(0),
      /**
       * <code>SUB = 1;</code>
       */
      SUB(1),
      /**
       * <code>MUL = 2;</code>
       */
      MUL(2),
      /**
       * <code>DIV = 3;</code>
       */
      DIV(3),
      ;

      /**
       * <code>SOM = 0;</code>
       */
      public static final int SOM_VALUE = 0;
      /**
       * <code>SUB = 1;</code>
       */
      public static final int SUB_VALUE = 1;
      /**
       * <code>MUL = 2;</code>
       */
      public static final int MUL_VALUE = 2;
      /**
       * <code>DIV = 3;</code>
       */
      public static final int DIV_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Operacao valueOf(int value) {
        return forNumber(value);
      }

      public static Operacao forNumber(int value) {
        switch (value) {
          case 0: return SOM;
          case 1: return SUB;
          case 2: return MUL;
          case 3: return DIV;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Operacao>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Operacao> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Operacao>() {
              public Operacao findValueByNumber(int number) {
                return Operacao.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ufc.sd.calc.Calculadora.Request.getDescriptor().getEnumTypes().get(0);
      }

      private static final Operacao[] VALUES = values();

      public static Operacao valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Operacao(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:br.ufc.quixada.calc.Request.Operacao)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int N1_FIELD_NUMBER = 2;
    private double n1_;
    /**
     * <code>required double n1 = 2;</code>
     */
    public boolean hasN1() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double n1 = 2;</code>
     */
    public double getN1() {
      return n1_;
    }

    public static final int N2_FIELD_NUMBER = 3;
    private double n2_;
    /**
     * <code>required double n2 = 3;</code>
     */
    public boolean hasN2() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double n2 = 3;</code>
     */
    public double getN2() {
      return n2_;
    }

    public static final int OP_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Integer> op_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        java.lang.Integer, ufc.sd.calc.Calculadora.Request.Operacao> op_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                java.lang.Integer, ufc.sd.calc.Calculadora.Request.Operacao>() {
              public ufc.sd.calc.Calculadora.Request.Operacao convert(java.lang.Integer from) {
                ufc.sd.calc.Calculadora.Request.Operacao result = ufc.sd.calc.Calculadora.Request.Operacao.valueOf(from);
                return result == null ? ufc.sd.calc.Calculadora.Request.Operacao.SOM : result;
              }
            };
    /**
     * <code>repeated .br.ufc.quixada.calc.Request.Operacao op = 4;</code>
     */
    public java.util.List<ufc.sd.calc.Calculadora.Request.Operacao> getOpList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, ufc.sd.calc.Calculadora.Request.Operacao>(op_, op_converter_);
    }
    /**
     * <code>repeated .br.ufc.quixada.calc.Request.Operacao op = 4;</code>
     */
    public int getOpCount() {
      return op_.size();
    }
    /**
     * <code>repeated .br.ufc.quixada.calc.Request.Operacao op = 4;</code>
     */
    public ufc.sd.calc.Calculadora.Request.Operacao getOp(int index) {
      return op_converter_.convert(op_.get(index));
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasN1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasN2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, n1_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, n2_);
      }
      for (int i = 0; i < op_.size(); i++) {
        output.writeEnum(4, op_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, n1_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, n2_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < op_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(op_.get(i));
        }
        size += dataSize;
        size += 1 * op_.size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ufc.sd.calc.Calculadora.Request)) {
        return super.equals(obj);
      }
      ufc.sd.calc.Calculadora.Request other = (ufc.sd.calc.Calculadora.Request) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasN1() == other.hasN1());
      if (hasN1()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getN1())
            == java.lang.Double.doubleToLongBits(
                other.getN1()));
      }
      result = result && (hasN2() == other.hasN2());
      if (hasN2()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getN2())
            == java.lang.Double.doubleToLongBits(
                other.getN2()));
      }
      result = result && op_.equals(other.op_);
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasN1()) {
        hash = (37 * hash) + N1_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getN1()));
      }
      if (hasN2()) {
        hash = (37 * hash) + N2_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getN2()));
      }
      if (getOpCount() > 0) {
        hash = (37 * hash) + OP_FIELD_NUMBER;
        hash = (53 * hash) + op_.hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ufc.sd.calc.Calculadora.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ufc.sd.calc.Calculadora.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ufc.sd.calc.Calculadora.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ufc.sd.calc.Calculadora.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ufc.sd.calc.Calculadora.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ufc.sd.calc.Calculadora.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ufc.sd.calc.Calculadora.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ufc.sd.calc.Calculadora.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ufc.sd.calc.Calculadora.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ufc.sd.calc.Calculadora.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ufc.sd.calc.Calculadora.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code br.ufc.quixada.calc.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:br.ufc.quixada.calc.Request)
        ufc.sd.calc.Calculadora.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ufc.sd.calc.Calculadora.internal_static_br_ufc_quixada_calc_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ufc.sd.calc.Calculadora.internal_static_br_ufc_quixada_calc_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ufc.sd.calc.Calculadora.Request.class, ufc.sd.calc.Calculadora.Request.Builder.class);
      }

      // Construct using ufc.sd.calc.Calculadora.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        n1_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        n2_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        op_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ufc.sd.calc.Calculadora.internal_static_br_ufc_quixada_calc_Request_descriptor;
      }

      public ufc.sd.calc.Calculadora.Request getDefaultInstanceForType() {
        return ufc.sd.calc.Calculadora.Request.getDefaultInstance();
      }

      public ufc.sd.calc.Calculadora.Request build() {
        ufc.sd.calc.Calculadora.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ufc.sd.calc.Calculadora.Request buildPartial() {
        ufc.sd.calc.Calculadora.Request result = new ufc.sd.calc.Calculadora.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.n1_ = n1_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.n2_ = n2_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          op_ = java.util.Collections.unmodifiableList(op_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.op_ = op_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ufc.sd.calc.Calculadora.Request) {
          return mergeFrom((ufc.sd.calc.Calculadora.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ufc.sd.calc.Calculadora.Request other) {
        if (other == ufc.sd.calc.Calculadora.Request.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasN1()) {
          setN1(other.getN1());
        }
        if (other.hasN2()) {
          setN2(other.getN2());
        }
        if (!other.op_.isEmpty()) {
          if (op_.isEmpty()) {
            op_ = other.op_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureOpIsMutable();
            op_.addAll(other.op_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasN1()) {
          return false;
        }
        if (!hasN2()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ufc.sd.calc.Calculadora.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ufc.sd.calc.Calculadora.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private double n1_ ;
      /**
       * <code>required double n1 = 2;</code>
       */
      public boolean hasN1() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double n1 = 2;</code>
       */
      public double getN1() {
        return n1_;
      }
      /**
       * <code>required double n1 = 2;</code>
       */
      public Builder setN1(double value) {
        bitField0_ |= 0x00000002;
        n1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double n1 = 2;</code>
       */
      public Builder clearN1() {
        bitField0_ = (bitField0_ & ~0x00000002);
        n1_ = 0D;
        onChanged();
        return this;
      }

      private double n2_ ;
      /**
       * <code>required double n2 = 3;</code>
       */
      public boolean hasN2() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double n2 = 3;</code>
       */
      public double getN2() {
        return n2_;
      }
      /**
       * <code>required double n2 = 3;</code>
       */
      public Builder setN2(double value) {
        bitField0_ |= 0x00000004;
        n2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double n2 = 3;</code>
       */
      public Builder clearN2() {
        bitField0_ = (bitField0_ & ~0x00000004);
        n2_ = 0D;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> op_ =
        java.util.Collections.emptyList();
      private void ensureOpIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          op_ = new java.util.ArrayList<java.lang.Integer>(op_);
          bitField0_ |= 0x00000008;
        }
      }
      /**
       * <code>repeated .br.ufc.quixada.calc.Request.Operacao op = 4;</code>
       */
      public java.util.List<ufc.sd.calc.Calculadora.Request.Operacao> getOpList() {
        return new com.google.protobuf.Internal.ListAdapter<
            java.lang.Integer, ufc.sd.calc.Calculadora.Request.Operacao>(op_, op_converter_);
      }
      /**
       * <code>repeated .br.ufc.quixada.calc.Request.Operacao op = 4;</code>
       */
      public int getOpCount() {
        return op_.size();
      }
      /**
       * <code>repeated .br.ufc.quixada.calc.Request.Operacao op = 4;</code>
       */
      public ufc.sd.calc.Calculadora.Request.Operacao getOp(int index) {
        return op_converter_.convert(op_.get(index));
      }
      /**
       * <code>repeated .br.ufc.quixada.calc.Request.Operacao op = 4;</code>
       */
      public Builder setOp(
          int index, ufc.sd.calc.Calculadora.Request.Operacao value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOpIsMutable();
        op_.set(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .br.ufc.quixada.calc.Request.Operacao op = 4;</code>
       */
      public Builder addOp(ufc.sd.calc.Calculadora.Request.Operacao value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOpIsMutable();
        op_.add(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .br.ufc.quixada.calc.Request.Operacao op = 4;</code>
       */
      public Builder addAllOp(
          java.lang.Iterable<? extends ufc.sd.calc.Calculadora.Request.Operacao> values) {
        ensureOpIsMutable();
        for (ufc.sd.calc.Calculadora.Request.Operacao value : values) {
          op_.add(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .br.ufc.quixada.calc.Request.Operacao op = 4;</code>
       */
      public Builder clearOp() {
        op_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:br.ufc.quixada.calc.Request)
    }

    // @@protoc_insertion_point(class_scope:br.ufc.quixada.calc.Request)
    private static final ufc.sd.calc.Calculadora.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ufc.sd.calc.Calculadora.Request();
    }

    public static ufc.sd.calc.Calculadora.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public ufc.sd.calc.Calculadora.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:br.ufc.quixada.calc.Reply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required double res = 2;</code>
     */
    boolean hasRes();
    /**
     * <code>required double res = 2;</code>
     */
    double getRes();
  }
  /**
   * Protobuf type {@code br.ufc.quixada.calc.Reply}
   */
  public  static final class Reply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:br.ufc.quixada.calc.Reply)
      ReplyOrBuilder {
    // Use Reply.newBuilder() to construct.
    private Reply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Reply() {
      id_ = 0;
      res_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Reply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              res_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ufc.sd.calc.Calculadora.internal_static_br_ufc_quixada_calc_Reply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ufc.sd.calc.Calculadora.internal_static_br_ufc_quixada_calc_Reply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ufc.sd.calc.Calculadora.Reply.class, ufc.sd.calc.Calculadora.Reply.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int RES_FIELD_NUMBER = 2;
    private double res_;
    /**
     * <code>required double res = 2;</code>
     */
    public boolean hasRes() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double res = 2;</code>
     */
    public double getRes() {
      return res_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, res_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, res_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ufc.sd.calc.Calculadora.Reply)) {
        return super.equals(obj);
      }
      ufc.sd.calc.Calculadora.Reply other = (ufc.sd.calc.Calculadora.Reply) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasRes() == other.hasRes());
      if (hasRes()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getRes())
            == java.lang.Double.doubleToLongBits(
                other.getRes()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasRes()) {
        hash = (37 * hash) + RES_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getRes()));
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ufc.sd.calc.Calculadora.Reply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ufc.sd.calc.Calculadora.Reply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ufc.sd.calc.Calculadora.Reply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ufc.sd.calc.Calculadora.Reply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ufc.sd.calc.Calculadora.Reply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ufc.sd.calc.Calculadora.Reply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ufc.sd.calc.Calculadora.Reply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ufc.sd.calc.Calculadora.Reply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ufc.sd.calc.Calculadora.Reply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ufc.sd.calc.Calculadora.Reply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ufc.sd.calc.Calculadora.Reply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code br.ufc.quixada.calc.Reply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:br.ufc.quixada.calc.Reply)
        ufc.sd.calc.Calculadora.ReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ufc.sd.calc.Calculadora.internal_static_br_ufc_quixada_calc_Reply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ufc.sd.calc.Calculadora.internal_static_br_ufc_quixada_calc_Reply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ufc.sd.calc.Calculadora.Reply.class, ufc.sd.calc.Calculadora.Reply.Builder.class);
      }

      // Construct using ufc.sd.calc.Calculadora.Reply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        res_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ufc.sd.calc.Calculadora.internal_static_br_ufc_quixada_calc_Reply_descriptor;
      }

      public ufc.sd.calc.Calculadora.Reply getDefaultInstanceForType() {
        return ufc.sd.calc.Calculadora.Reply.getDefaultInstance();
      }

      public ufc.sd.calc.Calculadora.Reply build() {
        ufc.sd.calc.Calculadora.Reply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ufc.sd.calc.Calculadora.Reply buildPartial() {
        ufc.sd.calc.Calculadora.Reply result = new ufc.sd.calc.Calculadora.Reply(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.res_ = res_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ufc.sd.calc.Calculadora.Reply) {
          return mergeFrom((ufc.sd.calc.Calculadora.Reply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ufc.sd.calc.Calculadora.Reply other) {
        if (other == ufc.sd.calc.Calculadora.Reply.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasRes()) {
          setRes(other.getRes());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasRes()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ufc.sd.calc.Calculadora.Reply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ufc.sd.calc.Calculadora.Reply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private double res_ ;
      /**
       * <code>required double res = 2;</code>
       */
      public boolean hasRes() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double res = 2;</code>
       */
      public double getRes() {
        return res_;
      }
      /**
       * <code>required double res = 2;</code>
       */
      public Builder setRes(double value) {
        bitField0_ |= 0x00000002;
        res_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double res = 2;</code>
       */
      public Builder clearRes() {
        bitField0_ = (bitField0_ & ~0x00000002);
        res_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:br.ufc.quixada.calc.Reply)
    }

    // @@protoc_insertion_point(class_scope:br.ufc.quixada.calc.Reply)
    private static final ufc.sd.calc.Calculadora.Reply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ufc.sd.calc.Calculadora.Reply();
    }

    public static ufc.sd.calc.Calculadora.Reply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Reply>
        PARSER = new com.google.protobuf.AbstractParser<Reply>() {
      public Reply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Reply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Reply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Reply> getParserForType() {
      return PARSER;
    }

    public ufc.sd.calc.Calculadora.Reply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_br_ufc_quixada_calc_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_br_ufc_quixada_calc_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_br_ufc_quixada_calc_Reply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_br_ufc_quixada_calc_Reply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021calculadora.proto\022\023br.ufc.quixada.calc" +
      "\"\220\001\n\007Request\022\n\n\002id\030\001 \002(\005\022\n\n\002n1\030\002 \002(\001\022\n\n\002" +
      "n2\030\003 \002(\001\0221\n\002op\030\004 \003(\0162%.br.ufc.quixada.ca" +
      "lc.Request.Operacao\".\n\010Operacao\022\007\n\003SOM\020\000" +
      "\022\007\n\003SUB\020\001\022\007\n\003MUL\020\002\022\007\n\003DIV\020\003\" \n\005Reply\022\n\n\002" +
      "id\030\001 \002(\005\022\013\n\003res\030\002 \002(\001B\032\n\013ufc.sd.calcB\013Ca" +
      "lculadora"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_br_ufc_quixada_calc_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_br_ufc_quixada_calc_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_br_ufc_quixada_calc_Request_descriptor,
        new java.lang.String[] { "Id", "N1", "N2", "Op", });
    internal_static_br_ufc_quixada_calc_Reply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_br_ufc_quixada_calc_Reply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_br_ufc_quixada_calc_Reply_descriptor,
        new java.lang.String[] { "Id", "Res", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
